import mongoose from "mongoose";
import dotenv from "dotenv";
import Role from "../models/roleModel.js";

dotenv.config();
const MONGO_URI = process.env.MONGO_URI || "mongodb://127.0.0.1:27017/stakeholderDB";

const roles = [
  { name: "Aceh Customary Council (Majelis Adat Aceh)" },
  { name: "Aceh Development Planning Agency (Bappeda)" },
  { name: "Aceh Energy and Mineral Resources Office (Dinas ESDM Aceh)" },
  { name: "Aceh Oil and Gas Management Agency (Badan Pengelola Migas Aceh/ BPMA)" },
  { name: "Aceh Regional Head of BIN (Kabinda Aceh)" },
  { name: "Aceh Reintegration Agency - BRA" },
  { name: "Aceh Ulama Consultative Assembly (MPU)" },
  { name: "BAIS (Strategic Intelligence, where relevant)" },
  { name: "Bank Perkreditan Rakyat (BPR)" },
  { name: "Bilateral Donors (USAID, GIZ, JICA)" },
  { name: "BPD (Village Consultative Council)" },
  { name: "BPH Migas" },
  { name: "BUMD PT. Bina Usaha (Regional Government-Owned Enterprise)" },
  { name: "BUMD PT. Pase Energi Migas (Regional Government-Owned Enterprise)" },
  { name: "BUMD PT. Pase Energi NSB (Regional Government-Owned Enterprise)" },
  { name: "BUMD PT. PEMA (Regional Government-Owned Enterprise)" },
  { name: "BUMD PT. Pembangunan Lhokseumawe (Regional Government-Owned Enterprise)" },
  { name: "BUMD PT. Rumah Sakit Arun Lhokseumawe (Regional Government-Owned Enterprise)" },
  { name: "Camat (District Head)" },
  { name: "Chief of the State Intelligence Agency (Kepala BIN)" },
  { name: "Community-Based Organizations (Karang Taruna, PKK, RT/RW forums)" },
  { name: "Coordinating Ministry for Community Empowerment (Kementerian Koordinator Bidang Pemberdayaan Masyarakat)" },
  { name: "Coordinating Ministry for Economic Affairs (Kementerian Koordinator Bidang Perekonomian)" },
  { name: "Coordinating Ministry for Food Affairs (Kementerian Koordinator Bidang Pangan)" },
  { name: "Coordinating Ministry for Human Development and Culture ((Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan)" },
  { name: "Coordinating Ministry for Infrastructure and Regional Development (Kementerian Koordinator Bidang Infrastruktur dan Pembangunan Kewilayahan)" },
  { name: "Coordinating Ministry for Law, Human Rights, Immigration, and Corrections (Kementerian Koordinator Bidang Hukum, HAM, Imigrasi, dan Pemasyarakatan)" },
  { name: "Coordinating Ministry for Political and Security Affairs (Kementerian Koordinator Bidang Politik dan Keamanan)" },
  { name: "CSR and Sustainability Consultants (Konsultan PPM)" },
  { name: "Cultural Preservation Groups (Kelompok Pelestari Budaya e.g., Adat Councils)" },
  { name: "Digital Media / Social Media Influencers" },
  { name: "Dinas Energi dan Sumber Daya Mineral Aceh/ Kabupaten (Energy and Mineral Resources Office)" },
  { name: "Dinas Kebudayaan dan Pariwisata Aceh/ Kabupaten (Culture and Tourism Office)" },
  { name: "Dinas Kependudukan dan Pencatatan Sipil Aceh/ Kabupaten (Population and Civil Registration Office)" },
  { name: "Dinas Kesehatan Aceh/ Kabupaten (Aceh Health Office)" },
  { name: "Dinas Komunikasi dan Informatika Aceh/ Kabupaten (Communication and Information Office)" },
  { name: "Dinas Koperasi dan Usaha Kecil Menengah Aceh/ Kabupaten (Cooperative and MSME Office)" },
  { name: "Dinas Lingkungan Hidup dan Kehutanan Aceh/ Kabupaten (Environment and Forestry Office)" },
  { name: "Dinas Pekerjaan Umum dan Penataan Ruang Aceh/ Kabupaten (Public Works and Spatial Planning Office)" },
  { name: "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Aceh/ Kabupaten (Investment and One-Stop Integrated Service Office)" },
  { name: "Dinas Pendidikan Aceh/ Kabupaten (Aceh Education Office)" },
  { name: "Dinas Pengelolaan Keuangan dan Aset Aceh/ Kabupaten (Finance and Asset Management Office)" },
  { name: "Dinas Perhubungan Aceh/ Kabupaten (Transportation Office)" },
  { name: "Dinas Perindustrian dan Perdagangan Aceh/ Kabupaten (Industry and Trade Office)" },
  { name: "Dinas Pertanian dan Perkebunan Aceh/ Kabupaten (Agriculture and Plantation Office)" },
  { name: "Dinas Sosial Aceh/ Kabupaten (Social Affairs Office)" },
  { name: "Directly Affected Communities (Masyarakat yang Terkena Dampak Langsung)" },
  { name: "Directly Affected People (Individu yang Terkena Dampak Langsung)" },
  { name: "District Community Leaders (Tokoh Masyarakat Kabupaten)" },
  { name: "District Government (Pemerintah Kecamatan)" },
  { name: "District Military Commander/ Chief (Kodim/Dandim)" },
  { name: "District Police Office/ Chief (Polres/ Kapolres)" },
  { name: "District Political Figures (Tokoh Politik Kabupaten)" },
  { name: "Education Foundations (Education Foundations)" },
  { name: "Engineering & Environmental Consultants (Konsultan Teknik & Lingkungan)" },
  { name: "Environmental and Forestry Office of Aceh (DLHK)" },
  { name: "Environmental Assessment Commission (Komisi AMDAL Nasional)" },
  { name: "Environmental NGOs (e.g., WALHI, Greenpeace)" },
  { name: "EPC firms and logistics providers" },
  { name: "Ex-Combatant Organizations (e.g., KPA)" },
  { name: "Export Credit Agency/ ECA (Lembaga Kredit Ekspor (LKE)" },
  { name: "Farmers’ and Fisherfolk Associations (Asosiasi Petani dan Nelayan)" },
  { name: "Foreign Embassies (Kedutaan Asing)" },
  { name: "Former Rebel Groups Turned Political Actors ( Kelompok Pemberontak Lama yang Beralih Menjadi Aktor Politik)" },
  { name: "Government PR Offices (Humas)" },
  { name: "Governor of Aceh" },
  { name: "Head of Departement (Kepala Dinas)" },
  { name: "Head of the Land Agency (Kepala Dinas Pertanahan)" },
  { name: "Head of the Regional Office of the State Intelligence Agency (Kabinda)" },
  { name: "Health, Safety, and Risk Management Firms (Perusahaan Kesehatan, Keselamatan, dan Manajemen Risiko)" },
  { name: "Human Rights Organizations (e.g., KontraS, LBH)" },
  { name: "Indigenous Communities (Masyarakat Adat)" },
  { name: "Industry Associations (Asosiasi Industri, e.g., KADIN, APINDO, IPA, IGA, IMA, ALFI)" },
  { name: "Industry Experts and Advisors (Ahli dan Penasihat Industri, e.g., IATMI, IAGI)" },
  { name: "Interfaith Forums (Forum Kerukunan Antaragama)" },
  { name: "International NGOs (WWF, Oxfam, etc.)" },
  { name: "Investment Agency (Lembaga Penanaman Modal)" },
  { name: "Islamic Organizations (NU, Muhammadiyah, Persis)" },
  { name: "Journalists and Press Associations (Wartawan/ Persatuan Wartawan)" },
  { name: "Junior and Elementary Schools (SMP, SD)" },
  { name: "Kepala Desa / Lurah (Village/Subdistrict Head)" },
  { name: "Labor Unions (Serikat Pekerja / Serikat Buruh e.g., FSPMI, KSBSI)" },
  { name: "Legal Advisors / Law Firms (Penasihat Hukum / Firma Hukum)" },
  { name: "Local Contractor (Kontraktor Lokal)" },
  { name: "Local Licensing (Kantor Perizinan Lokal)" },
  { name: "Local SMEs (UMKM Local)" },
  { name: "Local Social Welfare Organizations (Organisasi Kesejahteraan Sosial Lokal, ex. Karang Taruna, Panti Asuhan, dll)" },
  { name: "Local Vendor (Vendor Lokal)" },
  { name: "Mayor (Walikota)" },
  { name: "Member of Regency/City House of Representatives (Anggota DPRK Kab/Kota)" },
  { name: "Member of the Provincial Legislative Council (Anggota DPRProvinsi)" },
  { name: "Members of the House of Representatives of the Republic of Indonesia (Anggota DPR RI)" },
  { name: "Military Resort Command/ Chief (Korem/ Danrem)" },
  { name: "Ministries (e.g., ESDM, KLHK, Bappenas, Finance, Trade, Home Affairs)" },
  { name: "Ministry of Administrative and Bureaucratic Reform (Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi)" },
  { name: "Ministry of Agrarian Affairs and Spatial Planning / National Land Agency (Kementerian Agraria dan Tata Ruang / BPN)" },
  { name: "Ministry of Agriculture (Kementerian Pertanian)" },
  { name: "Ministry of Basic and Secondary Education (Kementerian Pendidikan Dasar dan Menengah)" },
  { name: "Ministry of Communication and Digital Affairs (Kementerian Komunikasi dan Digital)" },
  { name: "Ministry of Cooperatives (Kementerian Koperasi)" },
  { name: "Ministry of Creative Economy (Kementerian Ekonomi Kreatif)" },
  { name: "Ministry of Culture (Kementerian Kebudayaan)" },
  { name: "Ministry of Defense (Kementerian Pertahanan)" },
  { name: "Ministry of Energy and Mineral Resources (Kementerian Energi dan Sumber Daya Mineral (ESDM))" },
  { name: "Ministry of Environment (Kementerian Lingkungan Hidup)" },
  { name: "Ministry of Environment and Forestry (Kementerian LHK)" },
  { name: "Ministry of Finance (Kementerian Keuangan)" },
  { name: "Ministry of Foreign Affairs (Kementerian Luar Negeri)" },
  { name: "Ministry of Forestry (Kementerian Kehutanan)" },
  { name: "Ministry of Health (Kementerian Kesehatan)" },
  { name: "Ministry of Higher Education, Science, and Technology (Kementerian Pendidikan Tinggi, Sains, dan Teknologi)" },
  { name: "Ministry of Home Affairs (Kementerian Dalam Negeri)" },
  { name: "Ministry of Housing and Settlement Areas (Kementerian Perumahan dan Kawasan Permukiman)" },
  { name: "Ministry of Human Rights (Kementerian Hak Asasi Manusia)" },
  { name: "Ministry of Immigration and Corrections (Kementerian Imigrasi dan Pemasyarakatan)" },
  { name: "Ministry of Industry (Kementerian Perindustrian)" },
  { name: "Ministry of Investment and Downstreaming (Kementerian Investasi dan Hilirisasi)" },
  { name: "Ministry of Law (Kementerian Hukum)" },
  { name: "Ministry of Manpower (Kementerian Ketenagakerjaan)" },
  { name: "Ministry of Marine Affairs and Fisheries (Kementerian Kelautan dan Perikanan)" },
  { name: "Ministry of Migrant Worker Protection (Kementerian Perlindungan Pekerja Migran Indonesia)" },
  { name: "Ministry of MSMEs (Kementerian Usaha Mikro, Kecil, dan Menengah)" },
  { name: "Ministry of National Development Planning / Bappenas (Kementerian Perencanaan Pembangunan Nasional / Bappenas)" },
  { name: "Ministry of Population and Family Planning (Kementerian Kependudukan dan Pembangunan Keluarga)" },
  { name: "Ministry of Public Works (Kementerian Pekerjaan Umum)" },
  { name: "Ministry of Religious Affairs (Kementerian Agama)" },
  { name: "Ministry of Religious Affairs (Regional Offices)" },
  { name: "Ministry of Social Affairs (Kementerian Sosial)" },
  { name: "Ministry of State Secretariat (Kementerian Sekretariat Negara)" },
  { name: "Ministry of State-Owned Enterprises (Kementerian Badan Usaha Milik Negara (BUMN))" },
  { name: "Ministry of Tourism (Kementerian Pariwisata)" },
  { name: "Ministry of Trade (Kementerian Perdagangan)" },
  { name: "Ministry of Transmigration (Kementerian Transmigrasi)" },
  { name: "Ministry of Transportation (Kementerian Perhubungan)" },
  { name: "Ministry of Villages and Disadvantaged Regions (Kementerian Desa dan Pembangunan Daerah Tertinggal)" },
  { name: "Ministry of Women’s Empowerment and Child Protection (Kementerian Pemberdayaan Perempuan dan Perlindungan Anak)" },
  { name: "Ministry of Youth and Sports (Kementerian Pemuda dan Olahraga)" },
  { name: "Multilateral Institutions (World Bank, ADB, UN Agencies)" },
  { name: "Multinational and national private companies (Chevron, Medco, Shell)" },
  { name: "National and Local Media Outlets (Kompas, Metro TV, local radio)" },
  { name: "National Development Planning Agency (Bappenas)" },
  { name: "National Disaster Management Agency (BNPB)" },
  { name: "National Land Agency (BPN)" },
  { name: "National Political Figures (Tokoh Politik Nasional)" },
  { name: "One-Stop Investment and Licensing Service (Dinas Perizinan)" },
  { name: "President of the Republic of Indonesia (Presiden RI)" },
  { name: "Private Religious Schools (Dayah/Pesantren/ Sekolah Agama)" },
  { name: "Private Universities (Perguruan Tinggi Swasta)" },
  { name: "Provincial Government (Pemprov)" },
  { name: "Provincial Parliament (DPRD Provinsi)" },
  { name: "Provincial Political Figures (Tokoh Politik Provinsi)" },
  { name: "Provincial Secretary (Sekda Provinsi)" },
  { name: "Public Information Services (PPID)" },
  { name: "Public Universities (Perguruan Tinggi Negeri)" },
  { name: "Regency Government (Pemerintah Kabupaten)" },
  { name: "Regency Head (Bupati)" },
  { name: "Regency/City Parliament (DPRD Kabupaten/Kota)" },
  { name: "Regency/City Secretary (Sekda Kab/Kota)" },
  { name: "Regional Coordinator of the State Intelligence Agency (Korwil BIN)" },
  { name: "Regional General Hospital (RSUD)" },
  { name: "Regional Government or Local Government (Pemerintah Daerah)" },
  { name: "Regional Limited Liability Company - Perseroda Pakat Beusaree" },
  { name: "Regional Public Corporation - Perumda Air Minum Tirta Pase" },
  { name: "Regional Public Corporation - Perumda PDAM Tirta Meulaboh" },
  { name: "Religious Courts (Pengadilan Agama)" },
  { name: "Religious Leaders (Ulama, Pastors, Monks)" },
  { name: "Religious Schools (Dayah, Pesantren, Madrasah)" },
  { name: "Research and Development Institutes (Lembaga Penelitian dan Pengembangan)" },
  { name: "Sector Police Chief (Kapolsek)" },
  { name: "Security Support Services (Badan Usaha Jasa Pengamanan)" },
  { name: "Social Affairs Office (Dinas Sosial)" },
  { name: "Special Regulatory Agencies - Badan Pengelola Migas Aceh" },
  { name: "State-Owned Enterprises (BUMN): Pertamina, PLN, PGN" },
  { name: "Sub-district Community Leaders (Tokoh Masyarakat Kecamatan)" },
  { name: "Sub-district military command/ Chief (Koramil/ Danramil)" },
  { name: "Sub-district Political Figures (Tokoh Politik Kecamatan)" },
  { name: "Sub-village Head (Kepala Dusun)" },
  { name: "Supplier Lokal (Pemasok Local)" },
  { name: "Technical and Vocational Schools (SMK, SMA)" },
  { name: "Technology Providers (Penyedia Teknologi)" },
  { name: "The House of Representatives of the Republic of Indonesia (DPR RI)" },
  { name: "Training Institutions (BLK, LPTK)" },
  { name: "Upstream Oil and Gas Special Task Force (Northern Sumatra Region) SKK Migas Sumbagut" },
  { name: "Vice President (Wakil Presiden)" },
  { name: "Village Community Leaders (Tokoh Masyarakat Desa)" },
  { name: "Village Consultative Body (Badan Permusyawaratan Desa/ Tuha Peut)" },
  { name: "Village Government Staff & Village-Owned Enterprises (BUMDes)" },
  { name: "Village Political Figures (Tokoh Politik Desa)" },
  { name: "Youth and Women’s Organizations (Organisasi Pemuda dan Perempuan)" },
  { name: "Military Commander (Pangdam)" },
  { name: "Head of DPR Aceh" },
  { name: "Head of Commission II DPR Aceh" },
  { name: "Head of Commission III DPR Aceh" },
  { name: "Head of Energy and Mineral Resources Agency" },
  { name: "Head of Environmental Agency" },
  { name: "Head of Manpower Agency" },
  { name: "Head of Regional Development Agency" }
];

mongoose.connect(MONGO_URI).then(async () => {
  console.log("MongoDB Connected");

  await Role.deleteMany();
  await Role.insertMany(roles);

  console.log("Role seeding completed.");
  process.exit();
}).catch(err => {
  console.error(err);
  process.exit(1);
});